version: "3.9"
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    networks:
      - myweb
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql
    ports:
      - "3306:3306" 
  php:
    build: ../Sharper_API
    restart: unless-stopped
    networks:
    - myweb
    volumes:
    - conf-php:/usr/local/etc/php
    - conf-php-fpm:/usr/local/etc/php-fpm.d
    - www-data:/var/www/html
    ports:
      - "8000:8000"
  apache:
    image: ubuntu/apache2:2.4-20.04_beta
    ports:
    - 3002:80
    - 443:443
    restart: unless-stopped
    command:
    - /bin/sh
    - -c
    - |
        a2enmod rewrite expires
        a2enmod remoteip; \
        { \
        echo 'RemoteIPHeader X-Forwarded-For'; \
        echo 'RemoteIPTrustedProxy 10.0.0.0/8'; \
        echo 'RemoteIPTrustedProxy 172.16.0.0/12'; \
        echo 'RemoteIPTrustedProxy 192.168.0.0/16'; \
        echo 'RemoteIPTrustedProxy 169.254.0.0/16'; \
        echo 'RemoteIPTrustedProxy 127.0.0.0/8'; \
        } > /etc/apache2/conf-available/remoteip.conf; \
        a2enconf remoteip; \
        a2enmod proxy
        a2enmod proxy_fcgi
        a2ensite 000-default
        apache2-foreground
    networks:
    - myweb
    volumes:
    - conf-apache-sites:/etc/apache2/sites-available
    - log-apache:/var/log/apache2
    - www-data:/var/www/html
    depends_on:
    - "mariadb"
    - "php"

volumes:
  conf-apache-sites:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './conf/apache/sites-available'

  conf-php:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './conf/php'

  conf-php-fpm:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './conf/php-fpm'

  log-apache:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './log/apache'

  www-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './html'
  persistent:
networks:
  myweb:
