version: "3.9"
services:
  db:
    image: mysql
    ports: 
      - "3306:3306"
    environment:
        MYSQL_DATABASE: myDb
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
    volumes:
        - ./dump:/docker-entrypoint-initdb.d
        - persistent:/var/lib/mysql
    networks:
        - default
  php:
    build: ./images/php-7.4.0fpm
    restart: unless-stopped
    networks:
    - myweb
    command:
    - /bin/sh
    - -c
    - |
        docker-php-ext-enable curl exif gd iconv intl json mysqli opcache zip
        echo "Extension installed. Starting php-fpm."
        php-fpm
    volumes:
    - conf-php:/usr/local/etc/php
    - conf-php-fpm:/usr/local/etc/php-fpm.d
    - www-data:/var/www/html
  apache:
    image: ubuntu/apache2:2.4-20.04_beta
    ports:
    - 3002:80
    - 443:443
    restart: unless-stopped
    command:
    - /bin/sh
    - -c
    - |
        a2enmod rewrite expires
        a2enmod remoteip; \
        { \
        echo 'RemoteIPHeader X-Forwarded-For'; \
        echo 'RemoteIPTrustedProxy 10.0.0.0/8'; \
        echo 'RemoteIPTrustedProxy 172.16.0.0/12'; \
        echo 'RemoteIPTrustedProxy 192.168.0.0/16'; \
        echo 'RemoteIPTrustedProxy 169.254.0.0/16'; \
        echo 'RemoteIPTrustedProxy 127.0.0.0/8'; \
        } > /etc/apache2/conf-available/remoteip.conf; \
        a2enconf remoteip; \
        a2enmod proxy
        a2enmod proxy_fcgi
        a2ensite 000-default
        apache2-foreground
    networks:
    - myweb
    volumes:
    - conf-apache-sites:/etc/apache2/sites-available
    - log-apache:/var/log/apache2
    - www-data:/var/www/html
    depends_on:
    - "db"
    - "php"

volumes:
  conf-apache-sites:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './conf/apache/sites-available'

  conf-php:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './conf/php'

  conf-php-fpm:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './conf/php-fpm'

  log-apache:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './log/apache'

  www-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './html'
  persistent:
networks:
  myweb:
